// Code generated by MockGen. DO NOT EDIT.
// Source: group.go
//
// Generated by this command:
//
//	mockgen -source=group.go -destination=mocks/mock_group.go -package=controllermocks
//

// Package controllermocks is a generated GoMock package.
package controllermocks

import (
	context "context"
	reflect "reflect"

	db "github.com/fair-n-square-co/transactions/internal/db"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockGroupDBClient is a mock of GroupDBClient interface.
type MockGroupDBClient struct {
	ctrl     *gomock.Controller
	recorder *MockGroupDBClientMockRecorder
}

// MockGroupDBClientMockRecorder is the mock recorder for MockGroupDBClient.
type MockGroupDBClientMockRecorder struct {
	mock *MockGroupDBClient
}

// NewMockGroupDBClient creates a new mock instance.
func NewMockGroupDBClient(ctrl *gomock.Controller) *MockGroupDBClient {
	mock := &MockGroupDBClient{ctrl: ctrl}
	mock.recorder = &MockGroupDBClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupDBClient) EXPECT() *MockGroupDBClientMockRecorder {
	return m.recorder
}

// CreateGroup mocks base method.
func (m *MockGroupDBClient) CreateGroup(ctx context.Context, group db.CreateGroupOptions) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, group)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockGroupDBClientMockRecorder) CreateGroup(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockGroupDBClient)(nil).CreateGroup), ctx, group)
}

// ListGroups mocks base method.
func (m *MockGroupDBClient) ListGroups(ctx context.Context) (*db.GroupList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", ctx)
	ret0, _ := ret[0].(*db.GroupList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockGroupDBClientMockRecorder) ListGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockGroupDBClient)(nil).ListGroups), ctx)
}
